apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  selector:
    matchLabels:
      app: position-tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - name: position-tracker
        image: 788000630483.dkr.ecr.us-east-1.amazonaws.com/fleetman-position-tracker:5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        readinessProbe:
          httpGet:
            path: /vehicles/
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  ports:
    - name: http
      port: 8080
  type: ClusterIP

